import './globals.css'
import type { Metadata } from 'next'
import { Inter, Montserrat } from 'next/font/google'

const usedFonts = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Furball Facts!',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={usedFonts.className}>{children}</body>
    </html>
  )
}
